image: node:latest

stages:
  - prebuild
  - build
  - deploy

prebuild_package:
  stage: prebuild
  script:
    - |
      {
        npm i
      }

build_package:
  stage: build
  script:
    - |
      {
        npm i -g typescript ts-node nodemon &&
        npm run build &&
        echo "Successfully built version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME}"
      }

# Publish the package. If the version in package.json has not yet been published, it will be
# published to THE NPM registry. If the version already exists, the publish command
# will fail and the existing package will not be updated.
publish_package:
  stage: deploy
  only:
    - master
  script:
    - |
      {
        npm install -g npm-cli-login &&
        npm-cli-login -u $K8S_SECRET_NPM_USERNAME -p $K8S_SECRET_NPM_TOKEN -e $K8S_SECRET_NPM_EMAIL &&
        npm run deploy &&
        echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to NPM"
      } || {
        echo "No new version of ${NPM_PACKAGE_NAME} published. This is most likely because version ${NPM_PACKAGE_VERSION} already exists in the NPM registry."; exit 1
      }
