# Generated by BSB from the saved portable schema.
from __future__ import annotations
import json
from typing import Any, Awaitable, Callable, Literal, Never, NotRequired, TypeAlias, TypedDict, Union, cast
from bsb.base import BSBService, ServiceClient
from bsb.observable import Trace
from bsb.schema import client_value

Default4ClientOnOnreversereturnableInput = TypedDict('Default4ClientOnOnreversereturnableInput', {'text': 'str'})

class Default4Client(ServiceClient):
    schema = json.loads('{"pluginId": "service-default4", "pluginName": "service-default4", "events": {"onReverseReturnable": {"type": "returnable", "category": "emitReturnableEvents", "description": "Reverse text string", "inputSchema": {"anyvaliVersion": "1.0", "schemaVersion": "1.1", "root": {"kind": "object", "properties": {"text": {"kind": "string"}}, "required": ["text"], "unknownKeys": "strip"}, "definitions": {}, "extensions": {"bsb": {"description": "Reverse input parameters"}}}, "outputSchema": {"anyvaliVersion": "1.0", "schemaVersion": "1.1", "root": {"kind": "string"}, "definitions": {}, "extensions": {"bsb": {"description": "Reversed text"}}}}}, "version": "1.0.0"}')

    def __init__(self, context: BSBService, target_plugin_name: str | None = None) -> None:
        super().__init__(target_plugin_name or 'service-default4', context, self.schema)

    async def on_onreversereturnable(self, handler: Callable[[Trace, Default4ClientOnOnreversereturnableInput], Awaitable[str]], *, obs: Trace | None = None, server_id: str | None = None) -> None:
        async def wrapped(trace, payload):
            return await handler(trace, client_value(self.schema['events']['onReverseReturnable']['inputSchema'], payload))
        await self.events.on_returnable_event('onReverseReturnable', wrapped, obs=obs, server_id=server_id)
