# Generated by BSB from the saved portable schema.
from __future__ import annotations
import json
from typing import Any, Awaitable, Callable, Literal, Never, NotRequired, TypeAlias, TypedDict, Union, cast
from bsb.base import BSBService, ServiceClient
from bsb.observable import Trace
from bsb.schema import client_value

Default3ClientOnCalculateInput = TypedDict('Default3ClientOnCalculateInput', {'a': 'float', 'b': 'float'})
Default3ClientOnreversereturnableInput = TypedDict('Default3ClientOnreversereturnableInput', {'text': 'str'})

class Default3Client(ServiceClient):
    schema = json.loads('{"pluginId": "service-default3", "pluginName": "service-default3", "events": {"calculate": {"type": "returnable", "category": "emitReturnableEvents", "description": "Calculate with two numbers", "inputSchema": {"anyvaliVersion": "1.0", "schemaVersion": "1.1", "root": {"kind": "object", "properties": {"a": {"kind": "number"}, "b": {"kind": "number"}}, "required": ["a", "b"], "unknownKeys": "strip"}, "definitions": {}, "extensions": {"bsb": {"description": "Calculate input parameters"}}}, "outputSchema": {"anyvaliVersion": "1.0", "schemaVersion": "1.1", "root": {"kind": "number"}, "definitions": {}, "extensions": {"bsb": {"description": "Calculation result"}}}}, "onReverseReturnable": {"type": "returnable", "category": "onReturnableEvents", "description": "Reverse a string", "inputSchema": {"anyvaliVersion": "1.0", "schemaVersion": "1.1", "root": {"kind": "object", "properties": {"text": {"kind": "string"}}, "required": ["text"], "unknownKeys": "strip"}, "definitions": {}, "extensions": {"bsb": {"description": "Reverse input parameters"}}}, "outputSchema": {"anyvaliVersion": "1.0", "schemaVersion": "1.1", "root": {"kind": "string"}, "definitions": {}, "extensions": {"bsb": {"description": "Reversed text"}}}}}, "version": "1.0.0"}')

    def __init__(self, context: BSBService, target_plugin_name: str | None = None) -> None:
        super().__init__(target_plugin_name or 'service-default3', context, self.schema)

    async def on_calculate(self, handler: Callable[[Trace, Default3ClientOnCalculateInput], Awaitable[float]], *, obs: Trace | None = None, server_id: str | None = None) -> None:
        async def wrapped(trace, payload):
            return await handler(trace, client_value(self.schema['events']['calculate']['inputSchema'], payload))
        await self.events.on_returnable_event('calculate', wrapped, obs=obs, server_id=server_id)

    async def onreversereturnable(self, payload: Default3ClientOnreversereturnableInput, timeout_seconds: float = 5, *, obs: Trace | None = None, server_id: str | None = None) -> str:
        value = await self.events.emit_event_and_return('onReverseReturnable', payload, timeout_seconds=timeout_seconds, obs=obs, server_id=server_id)
        return cast('str', client_value(self.schema['events']['onReverseReturnable']['outputSchema'], value))
