// Code generated by BSB. DO NOT EDIT.
pub mod service_benchmarkify;
pub mod service_default0;
pub mod service_default1;
pub mod service_default2;
pub mod service_default3;
pub mod service_default4;
pub mod service_demo_todo;
