// Code generated by BSB. DO NOT EDIT.
#[derive(Clone, Debug, bsb::serde::Serialize, bsb::serde::Deserialize)]
#[serde(crate = "bsb::serde")]
pub struct ServiceDefault4ClientOnOnReverseReturnableInput {
    #[serde(rename = "text")]
    pub text: String,
}

#[derive(Clone)]
pub struct ServiceDefault4Client {
    events: bsb::events::Events,
}
impl ServiceDefault4Client {
    pub fn new(parent: &bsb::events::Events, target: Option<&str>) -> bsb::Result<Self> {
        let contract = bsb::serde_json::from_str(
            "{\r\n  \"pluginId\": \"service-default4\",\r\n  \"pluginName\": \"service-default4\",\r\n  \"events\": {\r\n    \"onReverseReturnable\": {\r\n      \"type\": \"returnable\",\r\n      \"category\": \"emitReturnableEvents\",\r\n      \"description\": \"Reverse text string\",\r\n      \"inputSchema\": {\r\n        \"anyvaliVersion\": \"1.0\",\r\n        \"schemaVersion\": \"1.1\",\r\n        \"root\": {\r\n          \"kind\": \"object\",\r\n          \"properties\": {\r\n            \"text\": {\r\n              \"kind\": \"string\"\r\n            }\r\n          },\r\n          \"required\": [\r\n            \"text\"\r\n          ],\r\n          \"unknownKeys\": \"strip\"\r\n        },\r\n        \"definitions\": {},\r\n        \"extensions\": {\r\n          \"bsb\": {\r\n            \"description\": \"Reverse input parameters\"\r\n          }\r\n        }\r\n      },\r\n      \"outputSchema\": {\r\n        \"anyvaliVersion\": \"1.0\",\r\n        \"schemaVersion\": \"1.1\",\r\n        \"root\": {\r\n          \"kind\": \"string\"\r\n        },\r\n        \"definitions\": {},\r\n        \"extensions\": {\r\n          \"bsb\": {\r\n            \"description\": \"Reversed text\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"version\": \"1.0.0\",\r\n  \"language\": \"rust\"\r\n}\r\n",
        )?;
        Ok(Self {
            events: parent.client(contract, target)?,
        })
    }
    pub fn specific(&self, id: &str) -> bsb::Result<Self> {
        Ok(Self {
            events: self.events.specific(id)?,
        })
    }
    pub fn events(&self) -> &bsb::events::Events {
        &self.events
    }
    pub async fn on_on_reverse_returnable<F, Fut>(&self, handler: F) -> bsb::Result<()>
    where
        F: Fn(bsb::observable::Observable, ServiceDefault4ClientOnOnReverseReturnableInput) -> Fut
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<Output = bsb::Result<String>> + Send + 'static,
    {
        let handler = std::sync::Arc::new(handler);
        self.events
            .listen(
                "onReverseReturnable",
                std::sync::Arc::new(move |obs, value| {
                    let handler = handler.clone();
                    Box::pin(async move {
                        let payload = bsb::serde_json::from_value::<
                            ServiceDefault4ClientOnOnReverseReturnableInput,
                        >(value)?;
                        let result = handler(obs, payload).await?;
                        Ok(bsb::serde_json::to_value(result)?)
                    })
                }),
            )
            .await
    }
}
