default:
  logging:
  events:
    rabbit:
      plugin: events-rabbitMQ
      package: "@bettercorp/bsb-rabbitmq"
      enabled: false
  services:
    service-default0X:
      plugin: service-default0
      enabled: true
      config: 
        testa: 5
        testb: 6
    service-default1X:
      plugin: service-default1
      enabled: true
    service-default2X:
      plugin: service-default2
      enabled: true
    service-default3X:
      plugin: service-default3
      enabled: true
