// Generated by BSB. Regenerate from the saved registry schema.
#nullable enable
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using BSB.Base;
using BSB.Interfaces;

public sealed record ServiceDefault4ClientOnOnReverseReturnableInput
{
    [JsonPropertyName("text")]
    public required string Text { get; init; }
}

public sealed class ServiceDefault4Client
{
    private readonly PluginEvents _events;
    private static readonly EventSchemaExport Schema = EventSchemaExport.FromJson("{\r\n  \u0022pluginId\u0022: \u0022service-default4\u0022,\r\n  \u0022pluginName\u0022: \u0022service-default4\u0022,\r\n  \u0022version\u0022: \u00221.0.0\u0022,\r\n  \u0022events\u0022: {\r\n    \u0022onReverseReturnable\u0022: {\r\n      \u0022category\u0022: \u0022emitReturnableEvents\u0022,\r\n      \u0022type\u0022: \u0022returnable\u0022,\r\n      \u0022inputSchema\u0022: {\r\n        \u0022anyvaliVersion\u0022: \u00221.0\u0022,\r\n        \u0022schemaVersion\u0022: \u00221.1\u0022,\r\n        \u0022root\u0022: {\r\n          \u0022kind\u0022: \u0022object\u0022,\r\n          \u0022properties\u0022: {\r\n            \u0022text\u0022: {\r\n              \u0022kind\u0022: \u0022string\u0022\r\n            }\r\n          },\r\n          \u0022required\u0022: [\r\n            \u0022text\u0022\r\n          ],\r\n          \u0022unknownKeys\u0022: \u0022strip\u0022\r\n        },\r\n        \u0022definitions\u0022: {},\r\n        \u0022extensions\u0022: {\r\n          \u0022bsb\u0022: {\r\n            \u0022description\u0022: \u0022Reverse input parameters\u0022\r\n          }\r\n        }\r\n      },\r\n      \u0022outputSchema\u0022: {\r\n        \u0022anyvaliVersion\u0022: \u00221.0\u0022,\r\n        \u0022schemaVersion\u0022: \u00221.1\u0022,\r\n        \u0022root\u0022: {\r\n          \u0022kind\u0022: \u0022string\u0022\r\n        },\r\n        \u0022definitions\u0022: {},\r\n        \u0022extensions\u0022: {\r\n          \u0022bsb\u0022: {\r\n            \u0022description\u0022: \u0022Reversed text\u0022\r\n          }\r\n        }\r\n      },\r\n      \u0022description\u0022: \u0022Reverse text string\u0022\r\n    }\r\n  }\r\n}");
    public ServiceDefault4Client(PluginEvents context, string targetPlugin = "service-default4")
        => _events = context.CreateClient(targetPlugin, Schema);
    private static T Convert<T>(object? value) => JsonSerializer.Deserialize<T>(JsonSerializer.Serialize(value), EventSchemaExport.JsonOptions)!;
    public Task OnOnReverseReturnable(IObservable obs, Func<IObservable, ServiceDefault4ClientOnOnReverseReturnableInput, Task<string>> handler) => _events.OnReturnableEvent("onReverseReturnable", obs, async (trace, value) => (object?)await handler(trace, Convert<ServiceDefault4ClientOnOnReverseReturnableInput>(value)));
    public Task OnOnReverseReturnableSpecific(string serverId, IObservable obs, Func<IObservable, ServiceDefault4ClientOnOnReverseReturnableInput, Task<string>> handler) => _events.OnReturnableEventSpecific(serverId, "onReverseReturnable", obs, async (trace, value) => (object?)await handler(trace, Convert<ServiceDefault4ClientOnOnReverseReturnableInput>(value)));

}