// Code generated by BSB. DO NOT EDIT.
package bsbclients

import (
	"context"
	"github.com/bettercorp/service-base/go/bsb"
)

type ServiceDefault4Client struct{ events *bsb.PluginEvents }

func NewServiceDefault4Client(parent *bsb.PluginEvents, target ...string) (*ServiceDefault4Client, error) {
	schemas, err := bsb.ImportEventSchemas([]byte("{\r\n  \"pluginId\": \"service-default4\",\r\n  \"pluginName\": \"service-default4\",\r\n  \"events\": {\r\n    \"onReverseReturnable\": {\r\n      \"type\": \"returnable\",\r\n      \"category\": \"emitReturnableEvents\",\r\n      \"description\": \"Reverse text string\",\r\n      \"inputSchema\": {\r\n        \"anyvaliVersion\": \"1.0\",\r\n        \"schemaVersion\": \"1.1\",\r\n        \"root\": {\r\n          \"kind\": \"object\",\r\n          \"properties\": {\r\n            \"text\": {\r\n              \"kind\": \"string\"\r\n            }\r\n          },\r\n          \"required\": [\r\n            \"text\"\r\n          ],\r\n          \"unknownKeys\": \"strip\"\r\n        },\r\n        \"definitions\": {},\r\n        \"extensions\": {\r\n          \"bsb\": {\r\n            \"description\": \"Reverse input parameters\"\r\n          }\r\n        }\r\n      },\r\n      \"outputSchema\": {\r\n        \"anyvaliVersion\": \"1.0\",\r\n        \"schemaVersion\": \"1.1\",\r\n        \"root\": {\r\n          \"kind\": \"string\"\r\n        },\r\n        \"definitions\": {},\r\n        \"extensions\": {\r\n          \"bsb\": {\r\n            \"description\": \"Reversed text\"\r\n          }\r\n        }\r\n      }\r\n    }\r\n  },\r\n  \"version\": \"1.0.0\",\r\n  \"language\": \"go\"\r\n}\r\n"), true)
	if err != nil {
		return nil, err
	}
	name := "service-default4"
	if len(target) > 0 {
		name = target[0]
	}
	events, err := parent.ClientTarget(name, schemas)
	if err != nil {
		return nil, err
	}
	return &ServiceDefault4Client{events: events}, nil
}
func (c *ServiceDefault4Client) Specific(serverID string) (*ServiceDefault4Client, error) {
	events, err := c.events.Specific(serverID)
	if err != nil {
		return nil, err
	}
	return &ServiceDefault4Client{events: events}, nil
}

type ServiceDefault4ClientOnOnReverseReturnableInput struct {
	Text string "json:\"text\""
}

func (c *ServiceDefault4Client) OnOnReverseReturnable(ctx context.Context, handler func(context.Context, bsb.Observable, ServiceDefault4ClientOnOnReverseReturnableInput) (string, error)) error {
	return c.events.OnReturnableEvent(ctx, "onReverseReturnable", func(ctx context.Context, obs bsb.Observable, value any) (any, error) {
		payload, err := bsb.DecodeValue[ServiceDefault4ClientOnOnReverseReturnableInput](value)
		if err != nil {
			return nil, err
		}
		result, err := handler(bsb.WithObservable(ctx, obs), obs, payload)
		if err != nil {
			return nil, err
		}
		return bsb.JSONValue(result)
	})
}
func (c *ServiceDefault4Client) Events() *bsb.PluginEvents { return c.events }
