name: Build Plugin

on:
  pull_request:
  workflow_dispatch:    

jobs:
  build_nodejs_plugin:
    uses: BetterCorp/service-base-build-workflows/.github/workflows/node.yml@master
    with:
      WORKING_DIR: ./nodejs
      PUBLISH: false

  docker_nodejs_plugin:
    needs: [build_nodejs_plugin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: ./ci-build-dist
        working-directory: ./nodejs

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: node-${{ needs.build_nodejs_plugin.outputs.tag }}-${{ needs.build_nodejs_plugin.outputs.version }}
          path: ./nodejs/ci-build-dist/

      - name: Extract artifact
        working-directory: ./nodejs
        run: |
          tar -xzf ./ci-build-dist/as-built.tar.gz -C ./

      - run: rm -rfv ./ci-build-dist
        working-directory: ./nodejs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./nodejs/
          file: ./nodejs/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: false
