name: Build Framework

on:
  push:
    branches:
      - "**"
      - "!develop"
      - "!master"
    tags-ignore:
      - "**"

jobs:
  build-framework:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm i -g typescript ts-node
      - run: tsc -v ; ts-node -v
      - run: npm ci
      - run: npm run build
      - run: npm run test

      - name: cleanup
        if: always()
        run: rm -f ~/.npmrc ; rm -f ./.npmrc;
